# Generated by Django 5.1.5 on 2025-01-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Занят'),
        ),
    ]
